// 和音の参考にしたサイト:https://virtualgirlmaki.wixsite.com/music/code
// ト音記号 単音
const GClefSingleTone = {
    "A,": "A<br>ラ",
    "B,": "B<br>シ",
    "C": "C<br>ド",
    "D": "D<br>レ",
    "E": "E<br>ミ",
    "F": "F<br>ファ",
    "G": "G<br>ソ",
    "A": "A<br>ラ",
    "B": "B<br>シ",
    "c": "C<br>ド",
    "d": "D<br>レ",
    "e": "E<br>ミ",
    "f": "F<br>ファ",
    "g": "G<br>ソ",
    "a": "A<br>ラ",
    "b": "B<br>シ",
    "c'": "C<br>ド",
};

// ト音記号 和音
const GClefHarmonyTone = {
    // メジャーコード
    "[A,^CE]": "A<br>AC♯E<br>ラド♯ミ",
    "[^A,DF]": "A♯ (B♭)<br>A♯DF<br>ラ♯レファ",
    "[B,^D^F]": "B<br>BD♯F♯<br>シレ♯ファ♯",
    "[CEG]": "C<br>CEG<br>ドミソ",
    "[^CF^G]": "C♯ (D♭)<br>C♯FG♯<br>ド♯ファソ♯",
    "[D^FA]": "D<br>DF♯A<br>レファ♯ラ",
    "[^DG^A]": "D♯ (E♭)<br>D♯GA♯<br>レ♯ソラ♯",
    "[E^GB]": "E<br>EG♯B<br>ミソ♯シ",
    "[FAc]": "F<br>FAC<br>ファラド",
    "[^F^A^c]": "F♯ (G♭)<br>F♯A♯C♯<br>ファ♯ラ♯ド♯",
    "[GBd]": "G<br>GBD<br>ソシレ",
    "[^Gc^d]": "G♯ (A♭)<br>G♯CD♯<br>ソ♯ドレ♯",
    "[A^ce]": "A<br>AC♯E<br>ラド♯ミ",
    "[^Adf]": "A♯ (B♭)<br>A♯DF<br>ラ♯レファ",
    "[B^d^f]": "B<br>BD♯F♯<br>シレ♯ファ♯",
    "[ceg]": "C<br>CEG<br>ドミソ",
    "[^cf^g]": "C♯ (D♭)<br>C♯FG♯<br>ド♯ファソ♯",
    "[d^fa]": "D<br>DF♯A<br>レファ♯ラ",
    "[^dg^a]": "D♯ (E♭)<br>D♯GA♯<br>レ♯ソラ♯",
    "[e^gb]": "E<br>EG♯B<br>ミソ♯シ",
    "[fac']": "F<br>FAC<br>ファラド",
    
    // マイナーコード
    "[A,CE]": "Am<br>ACE<br>ラドミ",
    "[^A,^CF]": "A♯m (B♭m)<br>A♯C♯F<br>ラ♯ド♯ファ",
    "[B,D^F]": "Bm<br>BDF♯<br>シレファ♯",
    "[C_EG]": "Cm<br>CE♭G<br>ドミ♭ソ",
    "[^CE^G]": "C♯m (D♭m)<br>C♯EG♯<br>ド♯ミソ♯",
    "[DFA]": "Dm<br>DFA<br>レファラ",
    "[^D^F^A]": "D♯m (E♭m)<br>D♯F♯A♯<br>レ♯ファ♯ラ♯",
    "[EGB]": "Em<br>EGB<br>ミソシ",
    "[F_Ac]": "Fm<br>FA♭C<br>ファラ♭ド",
    "[^FA^c]": "F♯m (G♭m)<br>F♯AC♯<br>ファ♯ラド♯",
    "[G_Bd]": "Gm<br>GB♭D<br>ソシ♭レ",
    "[^GB^d]": "G♯m (A♭m)<br>G♯BD♯<br>ソ♯シレ♯",
    "[Ace]": "Am<br>ACE<br>ラドミ",
    "[^A^cf]": "A♯m (B♭m)<br>A♯C♯F<br>ラ♯ド♯ファ",
    "[Bd^f]": "Bm<br>BDF♯<br>シレファ♯",
    "[c_eg]": "Cm<br>CE♭G<br>ドミ♭ソ",
    "[^ce^g]": "C♯m (D♭m)<br>C♯EG♯<br>ド♯ミソ♯",
    "[dfa]": "Dm<br>DFA<br>レファラ",
    "[^d^f^a]": "D♯m (E♭m)<br>D♯F♯A♯<br>レ♯ファ♯ラ♯",
    "[egb]": "Em<br>EGB<br>ミソシ",
    "[f_ac']": "Fm<br>FA♭C<br>ファラ♭ド",
    
    // セブンスコード
    "[A,^CEG]": "A7<br>AC♯EG<br>ラド♯ミソ",
    "[^A,DF^G]": "A♯7 (B♭7)<br>A♯DFG♯<br>ラ♯レファソ♯",
    "[B,^D^FA]": "B7<br>BD♯F♯A<br>シレ♯ファ♯ラ",
    "[CEG_B]": "C7<br>CEGB♭<br>ドミソシ♭",
    "[^CF^GB]": "C♯7 (D♭7)<br>C♯FG♯B<br>ド♯ファソ♯シ",
    "[D^FAc]": "D7<br>DF♯AC<br>レファ♯ラド",
    "[^DG^A^c]": "D♯7 (E♭7)<br>D♯GA♯C♯<br>レ♯ソラ♯ド♯",
    "[E^GBd]": "E7<br>EG♯BD<br>ミソ♯シレ",
    "[FAc_e]": "F7<br>FACE♭<br>ファラドミ♭",
    "[^F^A^ce]": "F♯7 (G♭7)<br>F♯A♯C♯E<br>ファ♯ラ♯ド♯ミ",
    "[GBdf]": "G7<br>GBDF<br>ソシレファ",
    "[^Gc^d^f]": "G♯7 (A♭7)<br>G♯CD♯F♯<br>ソ♯ドレ♯ファ♯",
    "[A^ceg]": "A7<br>AC♯EG<br>ラド♯ミソ",
    "[^Adf^g]": "A♯7 (B♭7)<br>A♯DFG♯<br>ラ♯レファソ♯",
    "[B^d^fa]": "B7<br>BD♯F♯A<br>シレ♯ファ♯ラ",
    "[ceg_b]": "C7<br>CEGB♭<br>ドミソシ♭",
    "[^cf^gb]": "C♯7 (D♭7)<br>C♯FG♯B<br>ド♯ファソ♯シ",
    "[d^fac']": "D7<br>DF♯AC<br>レファ♯ラド",
    
    // マイナーセブンスコード
    "[A,CEG]": "Am7<br>ACEG<br>ラドミソ",
    "[^A,^CF^G]": "A♯m7 (B♭m7)<br>A♯C♯FG♯<br>ラ♯ド♯ファソ♯",
    "[B,D^FA]": "Bm7<br>BDF♯A<br>シレファ♯ラ",
    "[C_EG_B]": "Cm7<br>CE♭GB♭<br>ドミ♭ソシ♭",
    "[^CE^GB]": "C♯m7 (D♭m7)<br>C♯EG♯B<br>ド♯ミソ♯シ",
    "[DFAc]": "Dm7<br>DFAC<br>レファラド",
    "[^D^F^A^c]": "D♯m7 (E♭m7)<br>D♯F♯A♯C♯<br>レ♯ファ♯ラ♯ド♯",
    "[EGBd]": "Em7<br>EGBD<br>ミソシレ",
    "[F_Ac_e]": "Fm7<br>FA♭CE♭<br>ファラ♭ドミ♭",
    "[^FA^ce]": "F♯m7 (G♭m7)<br>F♯AC♯E<br>ファ♯ラド♯ミ",
    "[G_Bdf]": "Gm7<br>GB♭DF<br>ソシ♭レファ",
    "[^GB^d^f]": "G♯m7 (A♭m7)<br>G♯BD♯F♯<br>ソ♯シレ♯ファ♯",
    "[Aceg]": "Am7<br>ACEG<br>ラドミソ",
    "[^A^cf^g]": "A♯m7 (B♭m7)<br>A♯C♯FG♯<br>ラ♯ド♯ファソ♯",
    "[Bd^fa]": "Bm7<br>BDF♯A<br>シレファ♯ラ",
    "[c_eg_b]": "Cm7<br>CE♭GB♭<br>ドミ♭ソシ♭",
    "[^ce^gb]": "C♯m7 (D♭m7)<br>C♯EG♯B<br>ド♯ミソ♯シ",
    "[dfac']": "Dm7<br>DFAC<br>レファラド",
};

// へ音記号 単音
const FClefSingleTone = {
    "C,,": "C<br>ド",
    "D,,": "D<br>レ",
    "E,,": "E<br>ミ",
    "F,,": "F<br>ファ",
    "G,,": "G<br>ソ",
    "A,,": "A<br>ラ",
    "B,,": "B<br>シ",
    "C,": "C<br>ド",
    "D,": "D<br>レ",
    "E,": "E<br>ミ",
    "F,": "F<br>ファ",
    "G,": "G<br>ソ",
    "A,": "A<br>ラ",
    "B,": "B<br>シ",
    "C": "C<br>ド",
    "D": "D<br>レ",
    "E": "E<br>ミ",
};

// へ音記号 和音
const FClefHarmonyTone = {
    // メジャーコード
    "[C,,E,,G,,]": "C<br>CEG<br>ドミソ",
    "[^C,,F,,^G,,]": "C♯ (D♭)<br>C♯FG♯<br>ド♯ファソ♯",
    "[D,,^F,,A,,]": "D<br>DF♯A<br>レファ♯ラ",
    "[^D,,G,,^A,,]": "D♯ (E♭)<br>D♯GA♯<br>レ♯ソラ♯",
    "[E,,^G,,B,,]": "E<br>EG♯B<br>ミソ♯シ",
    "[F,,A,,C,]": "F<br>FAC<br>ファラド",
    "[^F,,^A,,^C,]": "F♯ (G♭)<br>F♯A♯C♯<br>ファ♯ラ♯ド♯",
    "[G,,B,,D,]": "G<br>GBD<br>ソシレ",
    "[^G,,C,^D,]": "G♯ (A♭)<br>G♯CD♯<br>ソ♯ドレ♯",
    "[A,,^C,E,]": "A<br>AC♯E<br>ラド♯ミ",
    "[^A,,D,F,]": "A♯ (B♭)<br>A♯DF<br>ラ♯レファ",
    "[B,,^D,^F,]": "B<br>BD♯F♯<br>シレ♯ファ♯",
    "[C,E,G,]": "C<br>CEG<br>ドミソ",
    "[^C,F,^G,]": "C♯ (D♭)<br>C♯FG♯<br>ド♯ファソ♯",
    "[D,^F,A,]": "D<br>DF♯A<br>レファ♯ラ",
    "[^D,G,^A,]": "D♯ (E♭)<br>D♯GA♯<br>レ♯ソラ♯",
    "[E,^G,B,]": "E<br>EG♯B<br>ミソ♯シ",
    "[F,A,C]": "F<br>FAC<br>ファラド",
    "[^F,^A,^C]": "F♯ (G♭)<br>F♯A♯C♯<br>ファ♯ラ♯ド♯",
    "[G,B,D]": "G<br>GBD<br>ソシレ",
    "[^G,C^D]": "G♯ (A♭)<br>G♯CD♯<br>ソ♯ドレ♯",
    "[A,^CE]": "A<br>AC♯E<br>ラド♯ミ",
    
    // マイナーコード
    "[C,,_E,,G,,]": "Cm<br>CE♭G<br>ドミ♭ソ",
    "[^C,,E,,^G,,]": "C♯m (D♭m)<br>C♯EG♯<br>ド♯ミソ♯",
    "[D,,F,,A,,]": "Dm<br>DFA<br>レファラ",
    "[^D,,^F,,^A,,]": "D♯m (E♭m)<br>D♯F♯A♯<br>レ♯ファ♯ラ♯",
    "[E,,G,,B,,]": "Em<br>EGB<br>ミソシ",
    "[F,,_A,,C,]": "Fm<br>FA♭C<br>ファラ♭ド",
    "[^F,,A,,^C,]": "F♯m (G♭m)<br>F♯AC♯<br>ファ♯ラド♯",
    "[G,,_B,,D,]": "Gm<br>GB♭D<br>ソシ♭レ",
    "[^G,,B,,^D,]": "G♯m (A♭m)<br>G♯BD♯<br>ソ♯シレ♯",
    "[A,,C,E,]": "Am<br>ACE<br>ラドミ",
    "[^A,,^C,F,]": "A♯m (B♭m)<br>A♯C♯F<br>ラ♯ド♯ファ",
    "[B,,D,^F,]": "Bm<br>BDF♯<br>シレファ♯",
    "[C,_E,G,]": "Cm<br>CE♭G<br>ドミ♭ソ",
    "[^C,E,^G,]": "C♯m (D♭m)<br>C♯EG♯<br>ド♯ミソ♯",
    "[D,F,A,]": "Dm<br>DFA<br>レファラ",
    "[^D,^F,^A,]": "D♯m (E♭m)<br>D♯F♯A♯<br>レ♯ファ♯ラ♯",
    "[E,G,B,]": "Em<br>EGB<br>ミソシ",
    "[F,_A,C]": "Fm<br>FA♭C<br>ファラ♭ド",
    "[^F,A,^C]": "F♯m (G♭m)<br>F♯AC♯<br>ファ♯ラド♯",
    "[G,_B,D]": "Gm<br>GB♭D<br>ソシ♭レ",
    "[^G,B,^D]": "G♯m (A♭m)<br>G♯BD♯<br>ソ♯シレ♯",
    "[A,CE]": "Am<br>ACE<br>ラドミ",
    
    // セブンスコード
    "[C,,E,,G,,_B,,]": "C7<br>CEGB♭<br>ドミソシ♭",
    "[^C,,F,,^G,,B,,]": "C♯7 (D♭7)<br>C♯FG♯B<br>ド♯ファソ♯シ",
    "[D,,^F,,A,,C,]": "D7<br>DF♯AC<br>レファ♯ラド",
    "[^D,,G,,^A,,^C,]": "D♯7 (E♭7)<br>D♯GA♯C♯<br>レ♯ソラ♯ド♯",
    "[E,,^G,,B,,D,]": "E7<br>EG♯BD<br>ミソ♯シレ",
    "[F,,A,,C,_E,]": "F7<br>FACE♭<br>ファラドミ♭",
    "[^F,,^A,,^C,E,]": "F♯7 (G♭7)<br>F♯A♯C♯E<br>ファ♯ラ♯ド♯ミ",
    "[G,,B,,D,F,]": "G7<br>GBDF<br>ソシレファ",
    "[^G,,C,^D,^F,]": "G♯7 (A♭7)<br>G♯CD♯F♯<br>ソ♯ドレ♯ファ♯",
    "[A,,^C,E,G,]": "A7<br>AC♯EG<br>ラド♯ミソ",
    "[^A,,D,F,^G,]": "A♯7 (B♭7)<br>A♯DFG♯<br>ラ♯レファソ♯",
    "[B,,^D,^F,A,]": "B7<br>BD♯F♯A<br>シレ♯ファ♯ラ",
    "[C,E,G,_B,]": "C7<br>CEGB♭<br>ドミソシ♭",
    "[^C,F,^G,B,]": "C♯7 (D♭7)<br>C♯FG♯B<br>ド♯ファソ♯シ",
    "[D,^F,A,C]": "D7<br>DF♯AC<br>レファ♯ラド",
    "[^D,G,^A,^C]": "D♯7 (E♭7)<br>D♯GA♯C♯<br>レ♯ソラ♯ド♯",
    "[E,^G,B,D]": "E7<br>EG♯BD<br>ミソ♯シレ",
    "[F,A,C_E]": "F7<br>FACE♭<br>ファラドミ♭",
    "[^F,^A,^CE]": "F♯7 (G♭7)<br>F♯A♯C♯E<br>ファ♯ラ♯ド♯ミ",
    
    // マイナーセブンスコード
    "[C,,_E,,G,,_B,,]": "Cm7<br>CE♭GB♭<br>ドミ♭ソシ♭",
    "[^C,,E,,^G,,B,,]": "C♯m7 (D♭m7)<br>C♯EG♯B<br>ド♯ミソ♯シ",
    "[D,,F,,A,,C,]": "Dm7<br>DFAC<br>レファラド",
    "[^D,,^F,,^A,,^C,]": "D♯m7 (E♭m7)<br>D♯F♯A♯C♯<br>レ♯ファ♯ラ♯ド♯",
    "[E,,G,,B,,D,]": "Em7<br>EGBD<br>ミソシレ",
    "[F,,_A,,C,_E,]": "Fm7<br>FA♭CE♭<br>ファラ♭ドミ♭",
    "[^F,,A,,^C,E,]": "F♯m7 (G♭m7)<br>F♯AC♯E<br>ファ♯ラド♯ミ",
    "[G,,_B,,D,F,]": "Gm7<br>GB♭DF<br>ソシ♭レファ",
    "[^G,,B,,^D,^F,]": "G♯m7 (A♭m7)<br>G♯BD♯F♯<br>ソ♯シレ♯ファ♯",
    "[A,,C,E,G,]": "Am7<br>ACEG<br>ラドミソ",
    "[^A,,^C,F,^G,]": "A♯m7 (B♭m7)<br>A♯C♯FG♯<br>ラ♯ド♯ファソ♯",
    "[B,,D,^F,A,]": "Bm7<br>BDF♯A<br>シレファ♯ラ",
    "[C,_E,G,_B,]": "Cm7<br>CE♭GB♭<br>ドミ♭ソシ♭",
    "[^C,E,^G,B,]": "C♯m7 (D♭m7)<br>C♯EG♯B<br>ド♯ミソ♯シ",
    "[D,F,A,C]": "Dm7<br>DFAC<br>レファラド",
    "[^D,^F,^A,^C]": "D♯m7 (E♭m7)<br>D♯F♯A♯C♯<br>レ♯ファ♯ラ♯ド♯",
    "[E,G,B,D]": "Em7<br>EGBD<br>ミソシレ",
    "[F,_A,C_E]": "Fm7<br>FA♭CE♭<br>ファラ♭ドミ♭",
    "[^F,A,^CE]": "F♯m7 (G♭m7)<br>F♯AC♯E<br>ファ♯ラド♯ミ",
};